[phases.setup]
nixPkgs = ["python3"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "gunicorn -c gunicorn.conf.py run:app"